version: "3.8"

volumes:
  order-service-mysql-volume:

services:
  order-service-mysql:
    image: mysql:8.3
    container_name: order-service-mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_USER: order_service_username
      MYSQL_PASSWORD: order_service_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - order-service-mysql-volume:/var/lib/mysql

  order-service:
    image: order-service-image
    container_name: order-service-container
    restart: always
    depends_on:
      - order-service-mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://order-service-mysql:3306/order_service
      SPRING_DATASOURCE_USERNAME: order_service_username
      SPRING_DATASOURCE_PASSWORD: order_service_password
    ports:
      - 8080:8080