# Application
spring:
  application:
    name: api-gateway

  # Spring Cloud Api Gateway
  cloud:
    gateway:
      routes:
        # order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        # inventory-service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**
          filters:
            - StripPrefix=1
        # discovery-service
        - id: discovery-service
          uri: http://discovery-service:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # discovery-service-static
        - id: discovery-service-static
          uri: http://discovery-service:8761
          predicates:
            - Path=/eureka/**
        # notification-service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

# Application
server:
  port: {SERVER_PORT}

# Spring Cloud Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus